<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>pb.HelloRequest</code>
 */
class HelloRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string q = 1;</code>
     */
    private $q = '';
    /**
     * <code>int32 n = 2;</code>
     */
    private $n = 0;

    public function __construct() {
        \GPBMetadata\Demo::initOnce();
        parent::__construct();
    }

    /**
     * <code>string q = 1;</code>
     */
    public function getQ()
    {
        return $this->q;
    }

    /**
     * <code>string q = 1;</code>
     */
    public function setQ($var)
    {
        GPBUtil::checkString($var, True);
        $this->q = $var;
    }

    /**
     * <code>int32 n = 2;</code>
     */
    public function getN()
    {
        return $this->n;
    }

    /**
     * <code>int32 n = 2;</code>
     */
    public function setN($var)
    {
        GPBUtil::checkInt32($var);
        $this->n = $var;
    }

}

