<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace GPBMetadata;

class Demo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a0a64656d6f2e70726f746f1202706222240a0c48656c6c6f5265" .
            "717565737412090a017118012001280912090a016e18022001280522270a" .
            "0a48656c6c6f5265706c79120c0a04636f6465180120012805120b0a036d" .
            "736718022001280932330a0444656d6f122b0a0548656c6c6f12102e7062" .
            "2e48656c6c6f526571756573741a0e2e70622e48656c6c6f5265706c7922" .
            "00620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

